### PR TITLE
Extension and enhancing email channels

### PR DESCRIPTION
**Pull request by MrGeneration**
This pull request introduces 2 new pages:

* Aliases (email addresses)
* system notifications (E-Mail Channel)

This is to loosen up the all new and enhanced accounts page for email channels. 
We'll now provide a step by step how to for adding accounts, further email addresses, deletion and updating.

This should cover most of the recent questions I have stumbled on and hopefully helps administrators to see the whole scope even better. It also brings small tips and hints on how to optimize the administration workflow.

@Ryan - can you please have a look at this and throw your toolgear at me if it's too bad? 🤓 🛠

*Sidenote: This pull request will be blocking me from beginning the soon to come gmail channel because I'll want to recycle and rely on specific pages (like filters, settings and aliases). This will make my life easier and reduce double maintenance on such information* 💪

### CODE REVIEW

**Comment by rlue** [comment]
Great work, Marcel! There is a lot of expertise contained in this PR, and I'm sure it was a lot of work. I think the main place for improvement is its readability, which comes down to two (very interconnected) issues: organization and brevity.

### Organization

> This pull request introduces 2 new pages:
>
> * Aliases (email addresses)
> * system notifications (E-Mail Channel)
>
> This is to loosen up the all new and enhanced accounts page for email channels.

The admin docs are structured in a way that mirrors the admin panel. Putting these new articles on the same level as Accounts / Filters / Signatures / Settings breaks this pattern.

I see that the goal weas to keep the "Accounts" page short, but by breaking this mirrored structure, it makes it hard for readers know where to look for information. If a new user can't find their way around the docs, then you (as the support guy) become the gatekeeper to all the information inside them, which increases your workload.

Which also leads me to point 2...

### Brevity

I wanted to see how long it would take to read them from start to finish, but I got bored after 90 seconds and just gave up. If I can't do it, our users can't, either. But we can't just start deleting stuff to make it shorter, so what do we do?

Let's break down **two types of documentation** first:

1. **Guides** should be read from beginning to end. These should be as short as possible. Explain less, use examples and pictures more. The product's UX design should help you keep it short, just like in [this iMac commercial from 1998](https://www.youtube.com/watch?v=2iyMf3tlKpU).

   If you really need to walk through a complicated process step-by-step, a screencast is a better format.

2. **Reference docs** can be long and exhaustive. This kind of documentation can give details and notes about every single option in a form or menu. The user usually won't read it from start to finish; instead, they'll want to know about one thing, and skip straight to that part.

These docs combine both guides and references into one long article, which makes it hard to read through, because you never know if it's safe to skip something. So the answer to the brevity problem is actually to **reorganize**! Try guides first, followed by reference pages:

* Channels
  * Email
    * Accounts: How do accounts, aliases, and notifications work? (Guide)
      * Reference: Account settings
      * Reference: Alias settings
      * Reference: Notification settings

---

Do you have it in your schedule to do this kind of restructuring, or would you like me to take a stab at it?

**Comment by MrGeneration** [comment]
Like discussed privately, you'll be stabbing it with a fork. :)

**Comment by rlue** [comment]
Sorry for the delay. As usual, I got quite carried away with the changes. -\_-'

My changes are in the [`rl/pr55-qa`](https://github.com/zammad/zammad-admin-documentation/tree/rl/pr55-qa) branch, which includes all four of your commits from this PR. Unfortunately, it got a little messy with the rebasing and all that; what do you think of just force-pushing that branch onto this one? That is:

```sh
$ git switch mh-enhance-email-channel
$ git reset --hard rl/pr55-qa
$ git push --force
```

Do you have time to look over it before we merge? I know you're in a bit of a hurry with gmail stuff... :\\

**Comment by MrGeneration** [comment]
Thank you so much for your effort!
I'll check out locally and have a look before merging. :)

**Comment by MrGeneration** [comment]
I did actually have 2 things: one for wording (regarding the channel wizard during setting Zammad up which is optional) and the screencast for a secondary mail address.

Especially the screencast felt wrong when it started to scroll vertically. I thus replaced it. Could you please check if you're good to go with that?

We can then force push into this branch and continue if you'd like.

**Comment by rlue** [comment]
> Self-hosted users **could** have already completed this step...

Does this mean that it's possible for users to skip this step during setup? If so, "may" would be better.

---

Dude this gif is great. How did you make it so small? Mine was like 2MB after all the optimizations I could do. Ran the same optimizations on your gif and got it down to like 500KB:

accounts-addresses-optimized

**Comment by rlue** [comment]
Fixed and force-pushed! Merge away. :)

**Comment by MrGeneration** [comment]
> Dude this gif is great. How did you make it so small? Mine was like 2MB after all the optimizations I could do. Ran the same optimizations on your gif and got it down to like 500KB

I didn't do anything special to it. I'm using a tool called "screen2gif" which is great for doing such stuff. The size really varies from small to "oopsie, too big" :D

Maybe it took less captures of my screen during recording which would make it smaller.

---

> Does this mean that it's possible for users to skip this step during setup? If so, "may" would be better.

okay, so be it :D
I see you also already fixed the wording. Great!

Ready to go if you are, I think you still need to approve. :)

**Pull request merged**
