### PR TITLE
Added official Zabbix integration with Zammad to documentation.

### PR DESCRIPTION
**Pull request by RogerTheUnicornHive**
Added official Zabbix integration with Zammad to documentation.

### CODE REVIEW

**Comment by MrGeneration** [comment]
Sorry but I'm confused.
Zammad has no Zabbix integration - so technically the part where you want to add this is in my opinion a wrong and miss leading place.

If I understand correctly, what your documentationary is about is on how to monitor Zammad with your Zabbix installation - correct?

**Comment by RogerTheUnicornHive** [comment]
Hello,
My apologies for confusion.
The aim of the integration is to allow events from Zabbix to create and update tickets in Zammad.

**Comment by MrGeneration** [comment]
Okay thanks.
Please allow me to take some time to verify the guide and think of a way on how to put this in the documentation.

While integration is not entirely correct as place, it's in my opinion the best choice at this moment.
I'll proberbly will find a way to integrate it while pointing out it's not a direct integration. (I'm just concered some users might be confused and start searching for that configuration point :D)

I'll get back to you asap.

**Comment by MrGeneration** [comment]
First of all, thank you very much for your time and contribution.
`develop` is quite old and, I'm afraid, rebasing to `master` and continuing from there will be a nightmare.

This is why I'd like to suggest you to create a new branch from the repositories `master` branch and add the changes.

Note: 
In my commits I already moved `zabbix,rst` for you (it now lives in /system/integrations/).
In the past `system-integrations.rst` also moved to `/system/integrations.rst`.

Those are the only two files that would be required in your commits.
I could commit them too, but I'd prefer to keep your name and references in the commits to provide the credits you deserve. :)

Sorry for the trouble as well.

**Comment by MrGeneration** [comment]
Closing in favor of https://github.com/zammad/zammad-admin-documentation/pull/56
Thank you very much!

**Pull request closed without merging**
