### PR TITLE
Fixes #408 - Added ticket priority handling

### LINKED ISSUE #408: Add new ticket priority management
The new ticket priority management area should be described (https://github.com/zammad/zammad/issues/4892):

- Where you will reach it?
- Add/Edit (maybe explain the special situation for the UI color/icon?)
- Set default for a new ticket

### PR DESCRIPTION
**Pull request by ralf401**

### CODE REVIEW

**Review by mgruner — APPROVED** [review]
Looks good! 

I only noticed a rendering issue: there is no margin below the screenshots. Maybe @dvuckovic could check this?

Bildschirmfoto 2023-11-28 um 08 01 11

Bildschirmfoto 2023-11-28 um 08 01 22

**Comment by mgruner** [comment]
Bildschirmfoto 2023-11-28 um 08 24 34

This is the inspection data of the element on my system. Could it be that the sphinx template CSS overrides our own?

**Comment by mgruner** [comment]
Bildschirmfoto 2023-11-28 um 08 26 24

It first loads our theme, then the sphinx one, and since the selectors have the same specifity, the last one wins.

This is

```
sphinx-build --version
sphinx-build 4.5.0
```

**Comment by ralf401** [comment]
> I only noticed a rendering issue: there is no margin below the screenshots. Maybe @dvuckovic could check this?

It looks like your local build is affected only. My local build looks ok as well as the uploded artifacts.

**Comment by dvuckovic** [comment]
Let me check this.

**Comment by dvuckovic** [comment]
@mgruner I also don't see any issues, and as @ralf401 stated the CI artifacts are also fine.

Perhaps there is something stuck locally in your `_build` directory, you could try to clean it:

```
make clean && make html
```

**Comment by mgruner** [comment]
That's precisely what I did, and it produces this output.

**Comment by dvuckovic** [comment]
@ralf401 Resolved, the issue was in an outdated Python dependency. Please proceed with the merge.

**Pull request merged**
