### PR TITLE
Update microsoft.rst

### PR DESCRIPTION
**Pull request by xoladone**
This is mandatory.

### CODE REVIEW

**Comment by MrGeneration** [comment]
I'm sorry, but can you provide a bit context on the issue? Because right now I can't understand it. :-X

**Comment by xoladone** [comment]
Thanks for the reply.
Don't know what changed, but now both logins and linking succeed.
Sorry for the inconvenience.

**Comment by MrGeneration** [comment]
No worries at all!
I just want to understand what the reason for the needed change is.

Is it stil required or did dark magic help to make it work? :)

**Comment by xoladone** [comment]
Nothing left to do. Magic fixed it. ;)

**Pull request closed without merging**
